# Generated by Django 4.2 on 2023-04-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.IntegerField()),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fam', models.TextField()),
                ('name', models.TextField()),
                ('otc', models.TextField()),
                ('phone', models.TextField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField()),
                ('beautyTitle', models.TextField()),
                ('title', models.TextField()),
                ('other_titles', models.TextField()),
                ('connect', models.TextField(blank=True)),
                ('level_winter', models.TextField(blank=True, max_length=2)),
                ('level_summer', models.TextField(blank=True, max_length=2)),
                ('level_autumn', models.TextField(blank=True, max_length=2)),
                ('level_spring', models.TextField(blank=True, max_length=2)),
                ('status', models.CharField(choices=[('NW', 'new'), ('PD', 'pending'), ('AC', 'accepted'), ('RJ', 'rejected')], default='NW')),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passes.coords')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(upload_to='images/')),
                ('title', models.TextField()),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passes.perevaladded')),
            ],
        ),
    ]
