# Generated by Django 4.2 on 2023-04-19 22:13

from django.db import migrations, models
import passes.models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0002_levels_rename_longtitude_coords_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(blank=True, upload_to=passes.models.upload_to),
        ),
    ]
