# Generated by Django 4.2 on 2023-04-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0003_alter_image_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passes.perevaladded')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passes.users')),
            ],
        ),
    ]
